"""Initial_db

Revision ID: 3ef923283ada
Revises: 
Create Date: 2022-11-24 00:39:58.865729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef923283ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('codigo_postal', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe')
    # ### end Alembic commands ###
